name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations on submitting your first issue! We will review your issue and get back to you as soon as possible. While waiting, please ensure your issue follows the [contributing guide](https://github.com/Ascendus/ascendus.github.io/blob/main/.github/CONTRIBUTING.md) and [code of conduct](https://github.com/Ascendus/ascendus.github.io/blob/main/.github/CODE_OF_CONDUCT.md).'
        pr-message: 'Thanks for submitting a pull request! We will review your changes as soon as possible. While waiting, please ensure your pull request follows the [contributing guide](https://github.com/Ascendus/ascendus.github.io/blob/main/.github/CONTRIBUTING.md) and [code of conduct](https://github.com/Ascendus/ascendus.github.io/blob/main/.github/CODE_OF_CONDUCT.md).'
